version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/shoop
  - source: ./shoop.conf
    destination: /etc/nginx/sites-enabled

hooks:
  BeforeInstall:
    - location: deployment/BeforeInstall.sh
      timeout: 1000
      runas: root

  ApplicationStart:
    - location: deployment/ApplicationStart.sh