version: 0.0
os: linux
files:
  - source: /
    destination: /home/shoop
hooks:
  BeforeInstall:
    - location: deployment/BeforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deployment/AfterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deployment/ApplicationStart.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deployment/ApplicationStop.sh
      timeout: 300
      runas: root
