databases:
  - name: shoop_db
    databaseName: shoop_production
    user: shoop

services:
  - type: web
    name: shoop_web
    env: ruby
    buildCommand: "./render-deploy-helpers/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shoop_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
